name: ChatClear
version: '${project.version}'
main: de.littleprogrammer.chatclear.ChatClear
api-version: '1.20'
authors: [LittleProgrammer]
description: A simple chat clearing plugin
website: lpmc.me
