name: ChatClear
version: '${project.version}'
main: de.littleprogrammer.chatclear.Main
api-version: '1.16'
authors: [LittleProgrammer]
description: A simple chat clearing plugin
website: lpmc.me
commands:
  clearChat:
    description: This command clears your chat
    permission: chatClear.clear
    aliases:
      - cc
      - clear
